name: Contexto
run-name: Â¡Kary esta aprendiendo a usar Contextos!
on: push
jobs:
  check-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF"
