name: Contexto
run-name: Â¡Estoy aprendiendo a usar Contextos!
on: push
jobs:
  check-mybranch:
    if: ${{ github.ref == 'refs/heads/aprendiendo-github-actions' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF"
